name: alwadi_food
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  get_it: ^8.2.0

  dart_either: ^2.0.0
  dots_indicator: ^4.0.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  go_router: ^16.1.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.0 # أضف هذا هنا لتكون جاهزة للتشغيل
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

# إعداد flutter_launcher_icons يجب أن يكون هنا في أعلى المستوى، ليس داخل flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-alwadi.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
