name: alwadi_food
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  intl: ^0.20.0
  open_filex: ^4.5.0
  path_provider: ^2.1.3
  printing: ^5.13.0
  pdf: ^3.11.0
  dart_either: ^2.0.0
  dots_indicator: ^4.0.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  go_router: ^16.1.0
  google_fonts: ^6.1.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.0.0
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  firebase_storage: ^13.0.4
  fl_chart: ^0.66.2
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  syncfusion_flutter_pdfviewer: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-alwadi.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null

flutter_intl:
  enabled: true

dependency_overrides:
  vector_math: ^2.2.0
